### PR TITLE
fix: replace npm start with npm run build for travis

### PR DESCRIPTION
**Pull request by frederikprijck**
This should fix https://github.com/HNeukermans/adal-ts/issues/20

However, shouldn't webpack we used instead of tsc ?

### CODE REVIEW

**Comment by HNeukermans** [comment]
Nice fix. This should keep the travis logs clean.

Use webpack instead of tsc? 
Not really needed. There is a difference between the two.
  
- tsc takes care of compiling, solely.
- Webpack compiles, bundles and makes sure the exposed bundle is an umd module that has adal-ts name.
  I use  this webpack to build for production.

FYI: this also means that npm run build is infact not really needed in the travis setup. However, it also doesn't do any harm.

**Comment by frederikprijck** [comment]
So to make sure I understand all of it correctly, what are you using the current `npm run build` for ?

**Comment by frederikprijck** [comment]
I'm still a bit confused,  sorry :(. Are we supposed to use webpack or tsc to build ? If I understand correctly we only need webpack to build the dist folder,  not tsc by itself?

**Comment by HNeukermans** [comment]
That is correct. We don't need tsc.  The `npm run build`  command can be removed from the pre install step in travis. But it is left there, because it doesn't do any harm.

concerning webpack:
We use webpack to: 

- build the dist folder. (The dist folder is then used to publish to npm. Publishing is **NOT** part of travis ci automation, but is done manually be me. 
- run the tests. Testing is part of of travis ci automation,

(building dist also means compiling ts, by means of awesome typescript loader rule)

**Pull request merged**
